server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: 111111
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://heritage.cpqe6sioasnt.ap-northeast-2.rds.amazonaws.com:3306/heritage?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: hanaro1234!!
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        default_batch_fetch_size: 500
logging:
  level:
    root: info
jwt:
  secret: 0mUet36qbTmKpG6lQPJJbij815G75KB2zwUim2U6Hjc=
  issuer: quswjdgma83@naver.com

app:
  key: ebfd212c9fc8a2c8774d9dee8c034bd7

naver:
  ocr:
    secret: cUdjQUZlYktYcE16QlhzWkF4cWZ6VWhLQmtnYVluVEg=
    url: https://uai2lypwa6.apigw.ntruss.com/custom/v1/31531/7581753b3f6e4191227c04d5d08f959eb74f3486b7cae387f4dbf3c6580c14d3/infer

