server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seniordb?characterEncoding=utf8
    username: user01
    password: 111111
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        default_batch_fetch_size: 500
logging:
  level:
    root: info
