server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
      password: 111111
  datasource:
    username: sa
    url: jdbc:h2:mem:test;MODE=MYSQL
  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        default_batch_fetch_size: 500
logging:
  level:
    root: info
jwt:
  secret: 0mUet36qbTmKpG6lQPJJbij815G75KB2zwUim2U6Hjc=
  issuer: quswjdgma83@naver.com
